######################################################################
# Automatically generated by qmake (2.01a) Mo 30. Jul 19:43:27 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += globalhotkey.h mainwindow.h textfilelogger.h
FORMS += mainwindow.ui
SOURCES += globalhotkey.cpp main.cpp mainwindow.cpp textfilelogger.cpp
# QMAKE_CXXFLAGS += -std=c++0x