
# Variables
TARGET = tag4
SOURCES = tag4.cpp
HEADERS = 

# First rule, default target
tag2: $(SOURCES) $(HEADERS)
	g++ -std=c++0x -o $(TARGET) $(SOURCES)


# Clean rule. Best practice to include this
clean: 
	rm -f $(TARGET)
